### PR TITLE
v0.2022.0421

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

My attempt to build the latest version of *mesas*.

### CODE REVIEW

**Comment by mcflugen** [comment]
@charman2 I think I have *mesas* building now for Linux and Mac. I was able to build it on my own *Mac* and ran the tests, which passed, but I can't say for certain if everything is working or not.

To get it to build really all I did was to first compile the *cdflib90* Fortran files, and then run `pip install`. You can see this in the *build.sh* file. Because I don't have access to a Windows machine right now, I turned off Windows builds but I'm pretty sure something similar would work there as well.

Anyway, please have a look and see if I'm on the right track.

**Comment by charman2** [comment]
@mcflugen Thank you thank you! Can you go ahead and turn the windows builds back on? The Conda-forge CI will attempt to compile on Windows. If that works I'll go ahead and merge this.

Thank you again!

**Comment by mcflugen** [comment]
@charman2 It's not quite that easy, unfortunately. To get it building on Windows we need to create a *bld.bat* file that does the equivalent of what *build.sh* does on Linux and Mac. I suspect it would be easiest to create a *CMakeLists.txt* alongside the existing *Makefile* then use *cmake* to build the *cdflib90* files.

I don't have access to a Windows machine right now so it would be just trial and error at this point. I'm happy to help but I won't be able to get to this until next week I'm afraid. 

I wonder if there is a @conda-forge/help-fortran channel that could point us in the right direction (I don't think there is)?

**Comment by charman2** [comment]
@mcflugen Got it. I'm tempted to go the trial-and-error route myself, but I'd be flailing in the dark. Thanks again for your help.

**Comment by charman2** [comment]
@mcflugen I appreciate your perseverance on this. I'm going to owe you a bottle of something nice!

**Comment by mcflugen** [comment]
> I appreciate your perseverance on this. I'm going to owe you a bottle of something nice!

@charman2 No problem! I'm going to try to find a Windows machine today and see if that helps tracking down this problem.

**Comment by mcflugen** [comment]
@charman2 Can you believe it? All checks have passed!

**Comment by mcflugen** [comment]
@charman2 It looks like this is working so I'm going to merge it. I'll generate a pull request into [charman2/mesas](https://github.com/charman2/mesas) with the changes I made to get *mesas* built on all of the platforms.

**Comment by mcflugen** [comment]
@charman2 Actually, I don't have write access to conda-forge/mesas-feedstock so I can't merge this pull request.

**Pull request merged**
